
steps:
# Build the Docker image and tag it for Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t',
    'europe-north1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/your-image-name:$COMMIT_SHA',
    '.'
  ]
# Push the built image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'push',
    'europe-north1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/your-image-name:$COMMIT_SHA'
  ]

options:
  logging: NONE

